services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot -w /var/lib/letsencrypt
      --email dhrgodms123@gmail.com --agree-tos --no-eff-email
      -d api.trivus.net"

  backend:
    image: haeeun/elo-community:latest
    container_name: backend
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      # Contracts artifacts (if needed at runtime)
      - ./packages/contracts/artifacts:/usr/src/app/artifacts:ro
      - ./packages/contracts/typechain-types:/usr/src/app/typechain-types:ro