name: elo

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      backend:
        condition: service_healthy

  # 1회 발급/수동 갱신용(컨테이너는 실행 후 종료될 수 있음)
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot -w /var/lib/letsencrypt --email dhrgodms123@gmail.com --agree-tos --no-eff-email --non-interactive -d api.trivus.net || true"

  backend:
    image: ${DOCKER_USERNAME}/elo-community:${IMAGE_TAG}
    container_name: backend
    restart: always
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:3000/health || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
