global:
  scrape_interval: 5s

scrape_configs:
  # NestJS metrics
  - job_name: 'nestjs'
    static_configs:
      - targets: ['backend-local:3000']  # 로컬 NestJS 컨테이너 이름과 포트

  # PostgreSQL exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Node exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
